name: Node.js Deployment

on: [push]

jobs:
  deploy:
    runs-on: windows-latest # Use "windows-latest" for Windows environment

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Install dependencies
      run: npm install

    - name: Run Node.js script
      run: node app.js
